//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 02:55:30 PM CDT 
//


package org.openrepose.filters.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:impersonation="http://docs.openrepose.org/repose/impersonation/v1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;
 *                     If present, the Rackspace Impersonation filter will not send a failing response when an invalid state
 *                     is reached.
 *                     Instead, the filter will add the data relating to the failure to a header and forward the
 *                     request to be handled by a different filter or service.
 *                     If not present, the filter will send a failing response when an invalid state is
 *                     reached.
 *                 &lt;/html:p&gt;
 * </pre>
 * 
 *             
 * 
 * <p>Java class for DelegatingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DelegatingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="quality" type="{http://docs.openrepose.org/repose/impersonation/v1.0}QualityType" default="0.5" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DelegatingType")
public class DelegatingType {

    @XmlAttribute
    protected Double quality;

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getQuality() {
        if (quality == null) {
            return  0.5D;
        } else {
            return quality;
        }
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQuality(Double value) {
        this.quality = value;
    }

}
