//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 02:55:30 PM CDT 
//


package org.openrepose.filters.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openrepose.filters.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openrepose.filters.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DelegatingType }
     * 
     */
    public DelegatingType createDelegatingType() {
        return new DelegatingType();
    }

    /**
     * Create an instance of {@link RackspaceImpersonation }
     * 
     */
    public RackspaceImpersonation createRackspaceImpersonation() {
        return new RackspaceImpersonation();
    }

    /**
     * Create an instance of {@link AuthenticationServer }
     * 
     */
    public AuthenticationServer createAuthenticationServer() {
        return new AuthenticationServer();
    }

}
