//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 02:55:30 PM CDT 
//


package org.openrepose.filters.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;html:p xmlns:html="http://www.w3.org/1999/xhtml" xmlns:impersonation="http://docs.openrepose.org/repose/impersonation/v1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;Defines a Rackspace Impersonation configuration&lt;/html:p&gt;
 * </pre>
 * 
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="delegating" type="{http://docs.openrepose.org/repose/impersonation/v1.0}DelegatingType" minOccurs="0"/>
 *         &lt;element name="authentication-server" type="{http://docs.openrepose.org/repose/impersonation/v1.0}AuthenticationServer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "delegating",
    "authenticationServer"
})
@XmlRootElement(name = "rackspace-impersonation")
public class RackspaceImpersonation {

    protected DelegatingType delegating;
    @XmlElement(name = "authentication-server", required = true)
    protected AuthenticationServer authenticationServer;

    /**
     * Gets the value of the delegating property.
     * 
     * @return
     *     possible object is
     *     {@link DelegatingType }
     *     
     */
    public DelegatingType getDelegating() {
        return delegating;
    }

    /**
     * Sets the value of the delegating property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelegatingType }
     *     
     */
    public void setDelegating(DelegatingType value) {
        this.delegating = value;
    }

    /**
     * Gets the value of the authenticationServer property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationServer }
     *     
     */
    public AuthenticationServer getAuthenticationServer() {
        return authenticationServer;
    }

    /**
     * Sets the value of the authenticationServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationServer }
     *     
     */
    public void setAuthenticationServer(AuthenticationServer value) {
        this.authenticationServer = value;
    }

}
